hello: compile
	./hello

compile: hello.c
	clang hello.c -o hello

sync:
	rsync -av . root@10.196.6.188:/root/Assignment1/part1                                                                                 